query ListAllDocuments @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it lists public documents.") {
  documents {
    id
    title
    description
    status
    uploadDate
    fileUrl
    tags
    category {
      name
    }
    uploader {
      displayName
      email
    }
  }
}

query GetMyUploadedDocuments @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it only retrieves their own documents.") {
  documents(where: {uploaderId: {eq_expr: "auth.uid"}}) {
    id
    title
    status
    uploadDate
    category {
      name
    }
  }
}

mutation CreateNewDocument($title: String!, $fileUrl: String!, $status: String!, $categoryId: UUID!, $description: String, $tags: [String!]) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as they can only create documents linked to their own account.") {
  document_insert(data: {
    title: $title,
    fileUrl: $fileUrl,
    status: $status,
    categoryId: $categoryId,
    uploaderId_expr: "auth.uid",
    uploadDate_expr: "request.time",
    description: $description,
    tags: $tags
  })
}

mutation ApproveDocument($documentId: UUID!, $notes: String) @auth(expr: "auth.token.userType == 'admin'") {
  approvalLog_insert(data: {
    documentId: $documentId,
    adminId_expr: "auth.uid",
    action: "Approved",
    actionDate_expr: "request.time",
    notes: $notes
  })
}